// NFL Teams List

module.exports = [
  "Dallas Cowboys",
  "New York Giants",
  "Washington Redskins",
  "Philadelphia Eagles",
  "Minnesota Vikings",
  "Green Bay Packers",
  "Detroit Lions",
  "Chicago Bears",
  "Atlanta Falcons",
  "New Orleans Saints",
  "Carolina Panthers",
  "Tampa Bay Buccaneers",
  "Los Angeles Rams",
  "Seattle Seahawks",
  "Arizona Cardinals",
  "San Francisco 49ers",
  "New England Patriots",
  "New York Jets",
  "Miami Dolphins",
  "Buffalo Bills",
  "Baltimore Ravens",
  "Cincinnati Bengals",
  "Cleveland Browns",
  "Pittsburgh Steelers",
  "Tennessee Titans",
  "Houston Texans",
  "Jacksonville Jaguars",
  "Indianapolis Colts",
  "Denver Broncos",
  "Kansas City Chiefs",
  "Oakland Raiders",
  "Los Angeles Chargers"
  ];
